In [1]:
import yfinance as yf

In [24]:
ticker = "BBDC4"
period = "5d"
ticker_obj = yf.Ticker(f"{ticker}.SA")

In [25]:
ticker_obj

yfinance.Ticker object <BBDC4.SA>

In [22]:
ticker_obj.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-05-19 00:00:00-03:00,37.455103,38.217674,37.346164,37.979988,24323000,0.000000,0.0
2025-05-20 00:00:00-03:00,38.009699,38.009699,37.494716,37.930470,17978200,0.000000,0.0
2025-05-21 00:00:00-03:00,37.821532,37.831438,36.860893,37.167900,20216400,0.000000,0.0
2025-05-22 00:00:00-03:00,37.276837,37.375875,36.781661,36.910408,22889800,0.000000,0.0
2025-05-23 00:00:00-03:00,36.246871,37.356068,36.009189,37.356068,20125900,0.000000,0.0
2025-05-26 00:00:00-03:00,37.257031,37.880954,37.177805,37.435295,6500400,0.000000,0.0
2025-05-27 00:00:00-03:00,37.930466,38.247378,37.504615,37.732395,14716300,0.000000,0.0
2025-05-28 00:00:00-03:00,37.712595,37.781919,37.336260,37.425392,14548200,0.000000,0.0
2025-05-29 00:00:00-03:00,37.296646,37.593751,36.989636,37.128288,17515300,0.000000,0.0
2025-05-30 00:00:00-03:00,37.266934,37.356066,36.732143,37.068863,31193800,0.000000,0.0
2025-06-02 00:00:00-03:00,37.324148,37.413322,36.690025,36.808926,23075800,0.096837,0.0
2025-06-03 00:00:00-03:00,36.670205,36.808923,36.442317,36.690022,23511000,0.000000,0.0
2025-06-04 00:00:00-03:00,36.828737,36.947638,36.333328,36.600849,17266700,0.000000,0.0
2025-06-05 00:00:00-03:00,36.660299,36.660299,36.045993,36.154984,24798200,0.000000,0.0
2025-06-06 00:00:00-03:00,36.135169,36.412597,35.966728,36.244160,18187900,0.000000,0.0
2025-06-09 00:00:00-03:00,36.135168,36.293699,35.540674,36.055901,23946500,0.000000,0.0
2025-06-10 00:00:00-03:00,36.500000,36.580002,35.970001,36.000000,20363600,1.833040,0.0
2025-06-11 00:00:00-03:00,35.970001,36.590000,35.740002,36.330002,16180000,0.000000,0.0
2025-06-12 00:00:00-03:00,36.090000,36.830002,36.060001,36.610001,21869400,0.000000,0.0
2025-06-13 00:00:00-03:00,36.169998,36.349998,35.910000,36.169998,14389900,0.000000,0.0
2025-06-16 00:00:00-03:00,36.529999,37.220001,36.520000,36.830002,17353400,0.000000,0.0
2025-06-17 00:00:00-03:00,36.990002,37.090000,36.770000,37.049999,19547100,0.000000,0.0
2025-06-18 00:00:00-03:00,36.930000,37.080002,36.709999,36.830002,19694400,0.000000,0.0

In [26]:
ticker_obj.history(period=period)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-06-12 00:00:00-03:00,16.209999,16.540001,16.139999,16.480000,38328100,0.0,0.0
2025-06-13 00:00:00-03:00,16.260000,16.450001,16.139999,16.290001,29855200,0.0,0.0
2025-06-16 00:00:00-03:00,16.440001,16.740000,16.420000,16.639999,25238300,0.0,0.0
2025-06-17 00:00:00-03:00,16.629999,16.889999,16.610001,16.889999,33555400,0.0,0.0
2025-06-18 00:00:00-03:00,16.629999,16.950001,16.610001,16.760000,32449600,0.0,0.0

In [50]:
def retorna_cotacao(ticker_id, period):
    ticker_obj_function = yf.Ticker(f"{ticker_id}.SA")
    hist = ticker_obj_function.history(period=period)["Close"]
    hist.index = hist.index.strftime("%Y-%m-%d")
    hist = round(hist, 2)

    if len(hist) > 30:
        slice_size = int(len(hist) / 30)
        hist = hist[::-slice_size][::-1]

    return hist.to_json()

In [51]:
hist_data = retorna_cotacao("BBDC4", "5d")
hist_data

'{"2025-06-12":16.48,"2025-06-13":16.29,"2025-06-16":16.64,"2025-06-17":16.89,"2025-06-18":16.76}'